export interface MenuItem1 {
  id: string | number;
  name: string;
  path: string;
  children: MenuSubItem[];
}

interface MenuSubItem extends MenuItem1 {
  category: string;
  icon: string;
  description: string;
}

export const mainMenu: MenuItem1[] = [
  {
    id: 0,
    name: "Home",
    path: "/",
    children: [],
  },
  {
    id: 1,
    name: "product",
    path: "#",
    children: [
      {
        id: 11,
        name: "Table Reservation System",
        path: "/Table-Reservation-System",
        category: "product",
        icon: "",
        description: "Break down any sized project into customized tasks",
        children: [],
      },
      {
        id: 12,
        name: "Kiosk System",
        path: "/Kiosk",
        category: "product",
        icon: "",
        description: "Break down any sized project into customized tasks",
        children: [],
      },
      {
        id: 13,
        name: "Custom software",
        path: "/CustomSoftware",
        category: "product",
        icon: "",
        description: "Break down any sized project into customized tasks",
        children: [],
      },
      // {
      //   id: 14,
      //   name: "tasks",
      //   path: "/products/tasks",
      //   category: "product",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 15,
      //   name: "tasks",
      //   path: "/products/tasks",
      //   category: "product",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 16,
      //   name: "tasks",
      //   path: "/products/tasks",
      //   category: "product",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 17,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 18,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 19,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 110,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 111,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 112,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
    ],
  },
  // {
  //   id: 2,
  //   name: "solutions",
  //   path: "#",
  //   children: [
  //     {
  //       id: 21,
  //       name: "Cashless Wallet",
  //       path: "CashlessWallet",
  //       category: "product",
  //       icon: "",
  //       description: "Break down any sized project into customized tasks",
  //       children: [],
  //     },
  //     {
  //       id: 22,
  //       name: "tasks",
  //       path: "/products/tasks",
  //       category: "product",
  //       icon: "",
  //       description: "Break down any sized project into customized tasks",
  //       children: [],
  //     },
  //     {
  //       id: 23,
  //       name: "tasks",
  //       path: "/products/tasks",
  //       category: "product",
  //       icon: "",
  //       description: "Break down any sized project into customized tasks",
  //       children: [],
  //     },
  //     // {
  //     //   id: 24,
  //     //   name: "tasks",
  //     //   path: "/products/tasks",
  //     //   category: "product",
  //     //   icon: "",
  //     //   description: "Break down any sized project into customized tasks",
  //     //   children: [],
  //     // },
  //     // {
  //     //   id: 25,
  //     //   name: "tasks",
  //     //   path: "/products/tasks",
  //     //   category: "product",
  //     //   icon: "",
  //     //   description: "Break down any sized project into customized tasks",
  //     //   children: [],
  //     // },
  //     // {
  //     //   id: 26,
  //     //   name: "tasks",
  //     //   path: "/products/tasks",
  //     //   category: "product",
  //     //   icon: "",
  //     //   description: "Break down any sized project into customized tasks",
  //     //   children: [],
  //     // },
  //     // {
  //     //   id: 27,
  //     //   name: "tasks",
  //     //   path: "/platforms/tasks",
  //     //   category: "platform",
  //     //   icon: "",
  //     //   description: "Break down any sized project into customized tasks",
  //     //   children: [],
  //     // },
  //     // {
  //     //   id: 28,
  //     //   name: "tasks",
  //     //   path: "/platforms/tasks",
  //     //   category: "platform",
  //     //   icon: "",
  //     //   description: "Break down any sized project into customized tasks",
  //     //   children: [],
  //     // },
  //     // {
  //     //   id: 29,
  //     //   name: "tasks",
  //     //   path: "/platforms/tasks",
  //     //   category: "platform",
  //     //   icon: "",
  //     //   description: "Break down any sized project into customized tasks",
  //     //   children: [],
  //     // },
  //     // {
  //     //   id: 210,
  //     //   name: "tasks",
  //     //   path: "/platforms/tasks",
  //     //   category: "platform",
  //     //   icon: "",
  //     //   description: "Break down any sized project into customized tasks",
  //     //   children: [],
  //     // },
  //     // {
  //     //   id: 211,
  //     //   name: "tasks",
  //     //   path: "/platforms/tasks",
  //     //   category: "platform",
  //     //   icon: "",
  //     //   description: "Break down any sized project into customized tasks",
  //     //   children: [],
  //     // },
  //     // {
  //     //   id: 212,
  //     //   name: "tasks",
  //     //   path: "/platforms/tasks",
  //     //   category: "platform",
  //     //   icon: "",
  //     //   description: "Break down any sized project into customized tasks",
  //     //   children: [],
  //     // },
  //   ],
  // },
  {
    id: 2,
    name: "Services",
    path: "#",
    children: [
      {
        id: 31,
        name: "Integration Services",
        path: "/IntegrationServices",
        category: "product",
        icon: "",
        description: "Break down any sized project into customized tasks",
        children: [],
      },
      // {
      //   id: 32,
      //   name: "tasks",
      //   path: "/products/tasks",
      //   category: "product",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 33,
      //   name: "tasks",
      //   path: "/products/tasks",
      //   category: "product",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 34,
      //   name: "tasks",
      //   path: "/products/tasks",
      //   category: "product",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 35,
      //   name: "tasks",
      //   path: "/products/tasks",
      //   category: "product",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 36,
      //   name: "tasks",
      //   path: "/products/tasks",
      //   category: "product",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 37,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 38,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 39,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 310,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 311,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
      // {
      //   id: 312,
      //   name: "tasks",
      //   path: "/platforms/tasks",
      //   category: "platform",
      //   icon: "",
      //   description: "Break down any sized project into customized tasks",
      //   children: [],
      // },
    ],
  },
  {
    id: 4,
    name: "About us",
    path: "/AboutUs",
    children: [],
  },
  {
    id: 5,
    name: "Become a partner",
    path: "/becomepartner",
    children: [],
  },
];

/**
 * getMenusByName
 *
 * @param name name: string
 * @returns Promise<MenuItem1[]>
 */
export async function getMenusByName(name: string): Promise<MenuItem1[]> {
  try {
    return mainMenu;
  } catch (err: any) {
    throw err;
  }
}
